// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . 3 3 . . . . . . . . 
. . . 3 . 3 . 3 . . . . . . . . 
. . 1 . 3 3 3 . . . 3 3 3 . . . 
. . . . 3 3 3 . . . . . . . . . 
. . . 3 3 . 3 . . . . . . . . . 
. . . 3 . 3 3 . . . . . . . . . 
. . . 3 . . 3 . . . . . . . . . 
. . . 3 3 3 . 3 . . . . . . . . 
. . . . . . . . 3 . . . . . . . 
. . . . . . . . . 3 3 . . . . . 
. . . . . . . . . . . 3 . . . . 
. . . . . . . . . . . . 3 . . . 
. . . . . . . . . . . . . 3 . . 
. . . . . . . . . . . . . 3 3 . 
`;
            case "image1":
            case "myImage":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......fb111111bf.......
......fbf111111fbf......
......fd1f1111f1df......
......fd11f11f11df......
......fb12411421bf......
......fc12211221cf......
.......fb111111bf.......
......fffc1b1b1ffff.....
....fc111cfffff111cf....
....f1b1b1ffff1b1b1f....
....f1f1f1ffff1f1f1f....
....b1b1b1ffff1b1b1b....
..........bfffbb........
..........bfffb.........
...........bffb.........
............bfb.........
.............f..........
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
